files {
    'loading.html',
    'config.js',
    'script.js',
    'style.css',
    'music/nodoubt-hellagood.mp3',
    'music/imagdrag-imsosorry.mp3',
    'music/legomovie.mp3',
    'music/macklemore.mp3',
    'music/blink182-damnit.mp3',
    'icon/crown.png',
    'icon/discord.png',
    'icon/facebook.png',
    'icon/music.png',
    'icon/person.png',
    'icon/tip.png',
    'icon/twitch.png',
    'icon/twitter.png',
    'icon/pixelated.png',
    'icon/youtube.png',
    'img/1.jpg',
    'img/2.jpg',
    'img/3.jpg',
}

loadscreen 'loading.html'
