Citizen.CreateThread(function()
    --Example 1: AddTextEntry('gameName', 'VEHICLE_NAME_HERE')
    --Example 2: AddTextEntry('f350', '2013 Ford F350')
    --AddTextEntry('2015polstang', "'15 Mustang GT'")
    AddTextEntry(GetHashKey('Mustang'), "'15 Mustang GT")
end)