function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    --Example 1: AddTextEntry('gameName', 'VEHICLE_NAME_HERE')
    --Example 2: AddTextEntry('f350', '2013 Ford F350')
    AddTextEntry('SFTSU', 'Ranger')
    AddTextEntry('SFBC1', 'Sheriff Supervisor')
    AddTextEntry('SFBC2', 'Sheriff Charger')
    AddTextEntry('SFBC3', 'Sheriff SUV')
    AddTextEntry('SFBC4', 'Sheriff CV')
    AddTextEntry('SFBC5', 'SFBC5')
    AddTextEntry('SFUM1', 'Unmarked SUV')
    AddTextEntry('SFUM2', 'Unmarked CV')
end)