function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    --Example 1: AddTextEntry('gameName', 'VEHICLE_NAME_HERE')
    --Example 2: AddTextEntry('f350', '2013 Ford F350')
    AddTextEntry('SFTSU', 'Ranger')
    AddTextEntry('SFBC1', 'SFBC1')
    AddTextEntry('SFBC2', 'SFBC2')
    AddTextEntry('SFBC3', 'SFBC3')
    AddTextEntry('SFBC4', 'SFBC4')
    AddTextEntry('SFBC5', 'SFBC5')
    AddTextEntry('SFUM1', 'SFUM1')
    AddTextEntry('SFUM2', 'SFUM2')
    AddTextEntry('SFUM1', 'SFUM1')
end)