local PlayerData		= {}
local gender = nil
local menuPool = nil
local mainMenu = nil

Citizen.CreateThread(function()
	while ESX == nil do
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(0)
	end

	while ESX.GetPlayerData().job == nil do
		Citizen.Wait(10)
	end

    PlayerData = ESX.GetPlayerData()
    populateOutfits()

    menuPool:Add(mainMenu)
    menuPool:RefreshIndex()

end)

local outfits = {
    ['Male LSPD Uniform (Long Sleeve)'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 36, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 58, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 144, 1 },
        },
    },
    ['Male LSPD Uniform (Short Sleeve)'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 4, 1 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 36, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 59, 1 },
            { 9, 14, 1 },
            { 10, 1, 1 },
            { 11, 150, 1 },
        },
    },
    ['Female LSPD Uniform (Short Sleeve)'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 35, 1 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 36, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 147, 1 },
        },
    },
    ['Male LSPD Jacket'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 47, 1 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 36, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 52, 1 },
            { 9, 3, 1 },
            { 10, 1, 1 },
            { 11, 40, 1 },
        },
    },
    ['Female LSPD Jacket'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 35, 1 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 54, 1 },
            { 9, 3, 1 },
            { 10, 1, 1 },
            { 11, 173, 1 },
        },
    },
    ['Male LSPD Traffic Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 18, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 20, 1 },
            { 4, 33, 2 },
            { 5, 49, 1 },
            { 6, 31, 1 },
            { 7, 9, 1 },
            { 8, 58, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 19, 1 },
        },
    },
    ['Male LSPD Motorcycle Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 18, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 23, 1 },
            { 4, 33, 2 },
            { 5, 49, 1 },
            { 6, 31, 1 },
            { 7, 9, 1 },
            { 8, 58, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 53, 1 },
        },
    },
    ['Female LSPD Motorcycle Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 18, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 32, 2 },
            { 5, 49, 1 },
            { 6, 10, 1 },
            { 7, 9, 1 },
            { 8, 35, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 37, 1 },
        },
    },
    ['Male LSPD Suit'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 39, 8 },
            { 8, 11, 1 },
            { 9, 25, 1 },
            { 10, 1, 1 },
            { 11, 5, 5 },
        },
    },
    ['Female LSPD Suit'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 8, 1 },
            { 4, 4, 4 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 1, 1 },
            { 8, 65, 2 },
            { 9, 24, 2 },
            { 10, 1, 1 },
            { 11, 25, 2 },
        },
    },
    ['Male LSPD Detective'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 81, 8 },
            { 9, 25, 1 },
            { 10, 1, 1 },
            { 11, 4, 1 },
        },
    },
    ['Male LSPD Detective (Vest)'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 42, 2 },
            { 9, 25, 1 },
            { 10, 1, 1 },
            { 11, 4, 1 },
        },
    },
    ['Female LSPD Detective'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 4, 4 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 7, 1 },
            { 8, 25, 6 },
            { 9, 27, 1 },
            { 10, 1, 1 },
            { 11, 29, 3 },
        },
    },
    ['Male LSPD Windbreaker'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 5 },
            { 5, 49, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 12, 1 },
            { 9, 21, 2 },
            { 10, 1, 1 },
            { 11, 36, 2 },
        },
    },
    ['Male LSPD K-9 Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 7 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 53, 2 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 2, 1 },
            { 8, 38, 1 },
            { 9, 15, 1 },
            { 10, 9, 1 },
            { 11, 103, 1 },
        },
    },
    ['Female LSPD K-9 Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 55, 2 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 2, 1 },
            { 8, 3, 1 },
            { 9, 1, 1 },
            { 10, 8, 1 },
            { 11, 94, 1 },
        },
    },
    ['Male SASP Lifeguard (Long Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 48, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 2 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 81, 2 },
        },
    },
    ['Male SASP Ranger (Long Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 48, 2 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 2 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 81, 1 },
        },
    },
    ['Male SASP Lifeguard (Short Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 4 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 48, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 2 },
            { 9, 14, 1 },
            { 10, 1, 1 },
            { 11, 82, 2 },
        },
    },
    ['Female SASP Lifeguard (Short Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 11, 7 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 50, 1 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 32, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 41, 2 },
        },
    },
    ['Male SASP Ranger (Short Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 4, 1 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 48, 2 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 2 },
            { 9, 14, 1 },
            { 10, 1, 1 },
            { 11, 82, 1 },
        },
    },
    ['Female SASP Ranger (Short Sleeve)'] = {
        category = 'SASP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 11, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 50, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 32, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 41, 1 },
        },
    },
    ['Male SASP Jacket'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 48, 2 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 66, 17 },
            { 9, 2, 3 },
            { 10, 1, 1 },
            { 11, 157, 2 },
        },
    },
    ['Female SASP Jacket'] = {
        category = 'SASP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 11, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 4, 1 },
            { 4, 50, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 46, 17 },
            { 9, 2, 3 },
            { 10, 1, 1 },
            { 11, 154, 2 },
        },
    },
    ['Male BCSO Uniform (Long Sleeve)'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 14, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 26, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 39, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 25, 1 },
        },
    },
    ['Male BCSO Uniform (Short Sleeve)'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 4, 1 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 26, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 45, 1 },
            { 9, 14, 1 },
            { 10, 1, 1 },
            { 11, 75, 1 },
        },
    },
    ['Female BCSO Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 42, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 53, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 111, 1 },
        },
    },
    ['Male BCSO Jacket HI-VIS'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 26, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 66, 1 },
            { 9, 3, 2 },
            { 10, 1, 1 },
            { 11, 157, 1 },
        },
    },
    ['Male BCSO Jacket'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 26, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 66, 1 },
            { 9, 3, 2 },
            { 10, 1, 1 },
            { 11, 157, 4 },
        },
    },
    ['Female BCSO Jacket'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 4, 1 },
            { 4, 42, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 46, 1 },
            { 9, 3, 2 },
            { 10, 1, 1 },
            { 11, 154, 4 },
        },
    },
    ['Male BCSO Motorcycle Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 18, 4 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 23, 1 },
            { 4, 33, 3 },
            { 5, 49, 1 },
            { 6, 31, 1 },
            { 7, 9, 1 },
            { 8, 39, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 25, 1 },
        },
    },
    ['Female BCSO Motorcycle Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 18, 4 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 32, 3 },
            { 5, 49, 1 },
            { 6, 10, 1 },
            { 7, 9, 1 },
            { 8, 52, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 111, 1 },
        },
    },
    ['Male BCSO K-9 Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 8 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 60, 2 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 39, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 184, 1 },
        },
    },
    ['Female BCSO K-9 Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 11, 8 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 55, 1 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 52, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 92, 1 },
        },
    },
    ['Male BCSO Suit'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 4 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 39, 9 },
            { 8, 11, 4 },
            { 9, 24, 1 },
            { 10, 1, 1 },
            { 11, 5, 2 },
        },
    },
    ['Female BCSO Suit'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 8, 1 },
            { 4, 4, 9 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 1, 1 },
            { 8, 65, 2 },
            { 9, 26, 1 },
            { 10, 1, 1 },
            { 11, 25, 3 },
        },
    },
    ['Male BCSO Detective'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 4 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 81, 9 },
            { 9, 24, 1 },
            { 10, 1, 1 },
            { 11, 4, 4 },
        },
    },
    ['Male BCSO Detective (Vest)'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 4 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 42, 3 },
            { 9, 24, 1 },
            { 10, 1, 1 },
            { 11, 4, 4 },
        },
    },
    ['Female BCSO Detective'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 4, 6 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 7, 1 },
            { 8, 8, 1 },
            { 9, 26, 1 },
            { 10, 1, 1 },
            { 11, 15, 16 },
        },
    },
    ['Male BCSO Deputy'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 31, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 1, 2 },
            { 5, 49, 1 },
            { 6, 39, 4 },
            { 7, 7, 1 },
            { 8, 89, 1 },
            { 9, 24, 1 },
            { 10, 1, 1 },
            { 11, 134, 1 },
        },
    },
    ['Male BCSO Windbreaker'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 1, 2 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 7, 1 },
            { 8, 66, 1 },
            { 9, 24, 1 },
            { 10, 1, 1 },
            { 11, 36, 5 },
        },
    },
    ['Male FIB Suit'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 1 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 11, 1 },
            { 8, 11, 1 },
            { 9, 23, 1 },
            { 10, 1, 1 },
            { 11, 5, 1 },
        },
    },
    ['Female FIB Suit'] = {
        category = 'FIB',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 8, 1 },
            { 4, 4, 1 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 1, 1 },
            { 8, 65, 3 },
            { 9, 25, 1 },
            { 10, 1, 1 },
            { 11, 25, 1 },
        },
    },
    ['Male FIB Agent'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 7, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 13, 13 },
            { 8, 17, 1 },
            { 9, 23, 1 },
            { 10, 1, 1 },
            { 11, 4, 4 },
        },
    },
    ['Female FIB Agent'] = {
        category = 'FIB',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 4, 1 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 1, 1 },
            { 8, 10, 1 },
            { 9, 25, 1 },
            { 10, 1, 1 },
            { 11, 28, 1 },
        },
    },
    ['Male Government Suit'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 1 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 116, 1 },
            { 8, 11, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 11, 1 },
        },
    },
    ['Female Government Suit'] = {
        category = 'FIB',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 8, 1 },
            { 4, 38, 1 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 87, 1 },
            { 8, 39, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 59, 1 },
        },
    },
    ['Male FIB Response'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 5 },
            { 5, 49, 1 },
            { 6, 11, 1 },
            { 7, 9, 1 },
            { 8, 42, 4 },
            { 9, 20, 4 },
            { 10, 1, 1 },
            { 11, 4, 4 },
        },
    },
    ['Male FIB Windbreaker'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 5 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 21, 1 },
            { 7, 7, 1 },
            { 8, 12, 4 },
            { 9, 21, 1 },
            { 10, 1, 1 },
            { 11, 36, 1 },
        },
    },
    ['Male FIB Police Uniform'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 48, 1 },
            { 5, 49, 1 },
            { 6, 55, 1 },
            { 7, 9, 1 },
            { 8, 38, 1 },
            { 9, 14, 1 },
            { 10, 1, 1 },
            { 11, 33, 1 },
        },
    },
    ['Male PIA Special Agent'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 11, 5 },
            { 5, 1, 1 },
            { 6, 11, 1 },
            { 7, 14, 1 },
            { 8, 12, 1 },
            { 9, 23, 2 },
            { 10, 1, 1 },
            { 11, 5, 5 },
        },
    },
    ['Female PIA Special Agent'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 4, 1 },
            { 4, 4, 5 },
            { 5, 1, 1 },
            { 6, 30, 1 },
            { 7, 1, 1 },
            { 8, 40, 3 },
            { 9, 21, 6 },
            { 10, 1, 1 },
            { 11, 25, 4 },
        },
    },
    ['Male PIA Police'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 6 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 53, 4 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 6, 1 },
            { 8, 89, 1 },
            { 9, 23, 2 },
            { 10, 1, 1 },
            { 11, 52, 3 },
        },
    },
    ['Female PIA Police'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 55, 4 },
            { 5, 1, 1 },
            { 6, 25, 1 },
            { 7, 7, 1 },
            { 8, 8, 1 },
            { 9, 25, 2 },
            { 10, 1, 1 },
            { 11, 74, 1 },
        },
    },
    ['Male PIA Response'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 6 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 50, 4 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 2, 1 },
            { 8, 38, 1 },
            { 9, 13, 5 },
            { 10, 1, 1 },
            { 11, 52, 3 },
        },
    },
    ['Male PIA Windbreaker'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 13, 1 },
            { 4, 50, 4 },
            { 5, 1, 1 },
            { 6, 55, 1 },
            { 7, 7, 1 },
            { 8, 29, 4 },
            { 9, 21, 3 },
            { 10, 1, 1 },
            { 11, 36, 4 },
        },
    },
    ['Female PIA Response'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 5, 10 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 2, 1 },
            { 8, 3, 1 },
            { 9, 8, 4 },
            { 10, 1, 1 },
            { 11, 74, 1 },
        },
    },
    ['Male PIA Uniform'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 47, 1 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 2, 1 },
            { 8, 38, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 99, 1 },
        },
    },
    ['Female PIA Uniform'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 49, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 2, 1 },
            { 8, 3, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 90, 1 },
        },
    },
    ['Male Border Patrol'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 1, 1 },
            { 4, 53, 1 },
            { 5, 49, 1 },
            { 6, 28, 1 },
            { 7, 2, 1 },
            { 8, 38, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 98, 1 },
        },
    },
    ['Female Border Patrol'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 0, 0 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 15, 1 },
            { 4, 55, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 2, 1 },
            { 8, 3, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 89, 1 },
        },
    },
    ['Male SEP Uniform'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 11, 6 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 5, 1 },
            { 4, 11, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 21, 2 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 20, 1 },
        },
    },
    ['Male LSPD Winter Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 47, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 39, 1 },
            { 4, 36, 1 },
            { 5, 1, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 58, 1 },
            { 9, 27, 1 },
            { 10, 1, 1 },
            { 11, 155, 1 },
        },
    },
    ['Female LSPD Winter Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 46, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 35, 1 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 35, 1 },
            { 9, 29, 1 },
            { 10, 1, 1 },
            { 11, 152, 1 },
        },
    },
    ['Male SAHP Winter Uniform'] = {
        category = 'SAHP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 9, 3 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 39, 1 },
            { 4, 26, 2 },
            { 5, 49, 1 },
            { 6, 16, 1 },
            { 7, 9, 1 },
            { 8, 54, 1 },
            { 9, 27, 3 },
            { 10, 1, 1 },
            { 11, 18, 4 },
        },
    },
    ['Female SAHP Winter Uniform'] = {
        category = 'SAHP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 9, 3 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 42, 3 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 32, 2 },
            { 9, 29, 3 },
            { 10, 1, 1 },
            { 11, 22, 4 },
        },
    },
    ['Male BCSO Winter Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 9, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 39, 1 },
            { 4, 26, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 45, 1 },
            { 9, 27, 2 },
            { 10, 1, 1 },
            { 11, 18, 3 },
        },
    },
    ['Female BCSO Winter Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 9, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 42, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 52, 1 },
            { 9, 29, 2 },
            { 10, 1, 1 },
            { 11, 22, 3 },
        },
    },
    ['Male SASP Ranger Winter Uniform'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 9, 4 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 39, 1 },
            { 4, 48, 2 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 1 },
            { 9, 27, 4 },
            { 10, 1, 1 },
            { 11, 18, 5 },
        },
    },
    ['Female SASP Ranger Winter Uniform'] = {
        category = 'SASP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 9, 4 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 50, 2 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 32, 1 },
            { 9, 29, 4 },
            { 10, 1, 1 },
            { 11, 22, 5 },
        },
    },
    ['Male SASP Lifeguard Winter Uniform'] = {
        category = 'SASP',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 3, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 39, 1 },
            { 4, 48, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 54, 1 },
            { 9, 27, 5 },
            { 10, 1, 1 },
            { 11, 18, 6 },
        },
    },
    ['Female SASP Lifeguard Winter Uniform'] = {
        category = 'SASP',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 6, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 50, 1 },
            { 5, 49, 1 },
            { 6, 53, 1 },
            { 7, 9, 1 },
            { 8, 32, 1 },
            { 9, 29, 5 },
            { 10, 1, 1 },
            { 11, 22, 6 },
        },
    },
    ['Male LSPD Bicycle Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 50, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 20, 1 },
            { 4, 13, 3 },
            { 5, 49, 1 },
            { 6, 3, 1 },
            { 7, 9, 1 },
            { 8, 38, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 94, 3 },
        },
    },
    ['Female LSPD Bicycle Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 48, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 32, 1 },
            { 4, 15, 3 },
            { 5, 49, 1 },
            { 6, 11, 1 },
            { 7, 9, 1 },
            { 8, 3, 1 },
            { 9, 2, 1 },
            { 10, 1, 1 },
            { 11, 85, 3 },
        },
    },
    ['Male BCSO Bicycle Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 50, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 20, 1 },
            { 4, 13, 2 },
            { 5, 49, 1 },
            { 6, 3, 1 },
            { 7, 9, 1 },
            { 8, 38, 1 },
            { 9, 15, 1 },
            { 10, 1, 1 },
            { 11, 95, 2 },
        },
    },
    ['Female BCSO Bicycle Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 48, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 32, 1 },
            { 4, 15, 4 },
            { 5, 49, 1 },
            { 6, 11, 1 },
            { 7, 9, 1 },
            { 8, 3, 1 },
            { 9, 2, 1 },
            { 10, 1, 1 },
            { 11, 86, 2 },
        },
    },
    ['Male LSPD Pilot Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 80, 2 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 17, 1 },
            { 4, 39, 3 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 68, 1 },
            { 9, 1, 1 },
            { 10, 16, 1 },
            { 11, 66, 3 },
        },
    },
    ['Female LSPD Pilot Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 79, 2 },
            { 1, 14, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 18, 1 },
            { 4, 39, 3 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 50, 1 },
            { 9, 1, 1 },
            { 10, 15, 1 },
            { 11, 60, 3 },
        },
    },
    ['Male BCSO Pilot Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 80, 3 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 97, 1 },
            { 4, 39, 3 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 44, 3 },
            { 9, 1, 1 },
            { 10, 16, 4 },
            { 11, 66, 3 },
        },
    },
    ['Female BCSO Pilot Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 79, 3 },
            { 1, 14, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 37, 1 },
            { 4, 39, 3 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 31, 3 },
            { 9, 1, 1 },
            { 10, 15, 4 },
            { 11, 60, 3 },
        },
    },
    ['Male LSPD SWAT Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 76, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 97, 1 },
            { 4, 32, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 111, 1 },
            { 8, 16, 1 },
            { 9, 16, 1 },
            { 10, 4, 1 },
            { 11, 50, 1 },
        },
    },
    ['Female LSPD SWAT Uniform'] = {
        category = 'LSPD',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 75, 1 },
            { 1, 26, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 112, 1 },
            { 4, 31, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 82, 1 },
            { 8, 16, 1 },
            { 9, 18, 1 },
            { 10, 12, 1 },
            { 11, 43, 1 },
        },
    },
    ['Male BCSO SWAT Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 76, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 97, 1 },
            { 4, 32, 2 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 111, 1 },
            { 8, 16, 1 },
            { 9, 28, 1 },
            { 10, 7, 1 },
            { 11, 50, 2 },
        },
    },
    ['Female BCSO SWAT Uniform'] = {
        category = 'BCSO',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 75, 2 },
            { 1, 26, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 112, 1 },
            { 4, 31, 2 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 82, 1 },
            { 8, 16, 1 },
            { 9, 30, 1 },
            { 10, 12, 4 },
            { 11, 43, 2 },
        },
    },
    ['Male FIB ATU Uniform'] = {
        category = 'FIB',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 40, 1 },
            { 1, 24, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 17, 1 },
            { 4, 32, 5 },
            { 5, 49, 1 },
            { 6, 36, 1 },
            { 7, 43, 1 },
            { 8, 16, 1 },
            { 9, 28, 4 },
            { 10, 11, 1 },
            { 11, 50, 2 },
        },
    },
    ['Female FIB ATU Uniform'] = {
        category = 'FIB',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 39, 1 },
            { 1, 26, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 18, 1 },
            { 4, 31, 5 },
            { 5, 49, 1 },
            { 6, 37, 2 },
            { 7, 30, 1 },
            { 8, 16, 1 },
            { 9, 30, 4 },
            { 10, 13, 1 },
            { 11, 43, 2 },
        },
    },
    ['Male NOOSE TRU Uniform'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 76, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 97, 1 },
            { 4, 38, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 111, 1 },
            { 8, 16, 1 },
            { 9, 17, 3 },
            { 10, 6, 1 },
            { 11, 54, 1 },
        },
    },
    ['Female NOOSE TRU Uniform'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 75, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 112, 1 },
            { 4, 37, 1 },
            { 5, 49, 1 },
            { 6, 26, 1 },
            { 7, 82, 1 },
            { 8, 16, 1 },
            { 9, 19, 3 },
            { 10, 12, 3 },
            { 11, 47, 1 },
        },
    },
    ['Male Juggernaut'] = {
        category = 'NOOSE',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 94, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 111, 4 },
            { 4, 85, 1 },
            { 5, 1, 1 },
            { 6, 14, 1 },
            { 7, 1, 1 },
            { 8, 98, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 187, 1 },
        },
    },
    ['Female Juggernaut'] = {
        category = 'NOOSE',
        ped = 'mp_f_freemode_01',
        props = {
            { 0, 93, 1 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 53, 1 },
            { 3, 128, 4 },
            { 4, 87, 1 },
            { 5, 1, 1 },
            { 6, 35, 1 },
            { 7, 1, 1 },
            { 8, 106, 1 },
            { 9, 1, 1 },
            { 10, 1, 1 },
            { 11, 189, 1 },
        },
    },
    ['Male LSPD Riot Uniform'] = {
        category = 'LSPD',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 82, 2 },
            { 1, 0, 0 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 31, 1 },
            { 4, 36, 1 },
            { 5, 49, 1 },
            { 6, 52, 1 },
            { 7, 9, 1 },
            { 8, 58, 1 },
            { 9, 13, 4 },
            { 10, 1, 1 },
            { 11, 150, 1 },
        },
    },
    ['Male BCSO Riot Uniform'] = {
        category = 'BCSO',
        ped = 'mp_m_freemode_01',
        props = {
            { 0, 82, 3 },
            { 1, 1, 1 },
            { 2, 0, 0 },
            { 3, 0, 0 },
        },
        components = {
            { 1, 1, 1 },
            { 3, 31, 1 },
            { 4, 60, 2 },
            { 5, 49, 1 },
            { 6, 25, 1 },
            { 7, 9, 1 },
            { 8, 39, 1 },
            { 9, 13, 2 },
            { 10, 1, 1 },
            { 11, 75, 1 },
        },
    },
    
    
}

local function setOutfit(outfit)
    local ped = PlayerPedId()

    RequestModel(outfit.ped)

    while not HasModelLoaded(outfit.ped) do
        Wait(0)
    end

    if GetEntityModel(ped) ~= GetHashKey(outfit.ped) then
        SetPlayerModel(PlayerId(), outfit.ped)
    end

    ped = PlayerPedId()

    for _, comp in ipairs(outfit.components) do
       SetPedComponentVariation(ped, comp[1], comp[2] - 1, comp[3] - 1, 0)
    end

    for _, comp in ipairs(outfit.props) do
        if comp[2] == 0 then
            ClearPedProp(ped, comp[1])
        else
            SetPedPropIndex(ped, comp[1], comp[2] - 1, comp[3] - 1, true)
        end
    end
end

local categoryOutfits = {}

function populateOutfits()
    for name, outfit in pairs(outfits) do
        if not categoryOutfits[outfit.category] then
            categoryOutfits[outfit.category] = {}
        end
        
        if string.find(PlayerData.sex, 'f', 1, true) ~= nil and string.find(name, 'Female', 1, true) then
            categoryOutfits[outfit.category][name] = outfit
        elseif PlayerData.sex == 'm' and string.find(name, 'Male', 1, true) then
            categoryOutfits[outfit.category][name] = outfit
        elseif string.find(name, 'Female', 1, true) ~=  nil then
            print('outfits ok')
        else 
            print("string.find", name)

            --print('Outfit menu did not populate correctly. Please contact admin.')
        end
    end

    menuPool = NativeUI.CreatePool()
    mainMenu = NativeUI.CreateMenu('EUP FiveM', 'Pick your outfit!')

    for name, list in pairs(categoryOutfits) do
        local subMenu = menuPool:AddSubMenu(mainMenu, name)

        for id, outfit in pairs(list) do
                outfit.item = NativeUI.CreateItem(id, 'Select this outfit.')
                subMenu:AddItem(outfit.item)
        end

        subMenu.OnItemSelect = function(sender, item, index)
            -- find the outfit
            for _, outfit in pairs(list) do
                if outfit.item == item then
                    CreateThread(function()
                        setOutfit(outfit)
                    end)
                end
            end
        end
    end

end

--[[
function determineGender() 
    local busy = true

    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin, jobSkin)
        if skin.sex == 0 then
            gender = 'Male'
        else
            gender = 'Female'
        end
        busy = false
    end)

    while busy == true do
        Citizen.Wait(5)
    end

end]]

RegisterCommand('eup', function()
    if PlayerData.job ~= nil and PlayerData.job.name == 'police' then
        mainMenu:Visible(not mainMenu:Visible())
    else
        ESX.ShowNotification('You are not a police officer.')
    end
end, false)

Citizen.CreateThread(function()
    while ESX == nil do
        Citizen.Wait(0)
    end

    --determineGender()

    while true do
        Wait(0)
        menuPool:ProcessMenus()
    end
end)
