function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	--Example 1: AddTextEntry('GAMENAME', 'VEHICLE_NAME_HERE')
    --Example 2: AddTextEntry('f350', '2013 Ford F350')
    AddTextEntry('Light s15', 'Nissan Silvia S15')
    AddTextEntry('RX7', "'84 Mazda RX-7")
    AddTextEntry('370Z', 'Nissan 370Z Nismo')
    AddTextEntry('Caprice', "'74 Chevy Caprice")
    AddTextEntry('gtrnismo17', 'Nissan GT-R Nismo')
    AddTextEntry('na6', 'Mazda MX Miata')
    AddTextEntry('Rs5', 'Audi RS 5')
    AddTextEntry('rs6', 'Audi RS 6')
    AddTextEntry('SSTI', 'Subaru WRX STI')
    AddTextEntry('KART', 'Go-Kart')
    AddTextEntry('Shifter_KART', 'Shifter Go-Kart')
    AddTextEntry('MUSTANG', 'Mustang GT')
    AddTextEntry('BMCI', 'BMW M5')
    AddTextEntry('CLS2015', 'Mercedes CLS')
    AddTextEntry('911r', 'Porsche 911')
    AddTextEntry('180sx', 'Nissan 180sx')
    AddTextEntry('RX7TUNABLE', 'Mazda Rx7')
    AddTextEntry('EVO9', 'Lancer Evo9')
    AddTextEntry('SUPRA2', 'Toyota Supra')
end)
