Config = {}

Config.AutomaticPayments = false
Config.InterestRate = 0.08
Config.PaymentBehindRepo = 6
Config.PaymentDays = 28
Config.MarkerDrawDistance = 20
Config.PaymentErrorThreshold = 100
Config.PaymentLocations = {
    PDM = {
        Coords = vector3(-29.79, -1103.59, 26.42),
        Sprite = 29,
        Scale = vector3(1.5, 1.5, 0.5),
        Color = { r = 0, g = 255, b = 0 },
    },
    BCS = {
        Coords = vector3(-107.26, 6468.98, 31.63),
        Sprite = 29,
        Scale = vector3(1.5, 1.5, 0.5),
        Color = { r = 0, g = 255, b = 0 },
    },
    Harmony = {
        Coords = vector3(1224.74, 2728.36, 38),
        Sprite = 29,
        Scale = vector3(1.5, 1.5, 0.5),
        Color = { r = 0, g = 255, b = 0 },
    }
}

exports('GetPaymentDays', function()
	return Config.PaymentDays
end)

function GetColor(colorID)
	local colors = {
			{ index = 0, label =  ('Black')},
			{ index = 1, label =  ('Graphite')},
			{ index = 2, label =  ('Black Metallic')},
			{ index = 3, label =  ('Cast Steel')},
			{ index = 11, label =  ('Black Anthracite')},
			{ index = 12, label =  ('Matte Black')},
			{ index = 15, label =  ('Dark Night')},
			{ index = 16, label =  ('Deep Black')},
			{ index = 21, label =  ('Oil')},
			{ index = 147, label =  ('Carbon')},
			{ index = 106, label =  ('Vanilla')},
			{ index = 107, label =  ('Creme')},
			{ index = 111, label =  ('White')},
			{ index = 112, label =  ('Polar White')},
			{ index = 113, label =  ('Beige')},
			{ index = 121, label =  ('Matte White')},
			{ index = 122, label =  ('Snow')},
			{ index = 131, label =  ('Cotton')},
			{ index = 132, label =  ('Alabaster')},
			{ index = 134, label =  ('Pure White')},
			{ index = 4, label =  ('Silver')},
			{ index = 5, label =  ('Metallic Grey')},
			{ index = 6, label =  ('Laminated Steel')},
			{ index = 7, label =  ('Dark Gray')},
			{ index = 8, label =  ('Rocky Gray')},
			{ index = 9, label =  ('Gray Night')},
			{ index = 10, label =  ('Aluminum')},
			{ index = 13, label =  ('Matte Gray')},
			{ index = 14, label =  ('Light Grey')},
			{ index = 17, label =  ('Asphalt Gray')},
			{ index = 18, label =  ('Gray Concrete')},
			{ index = 19, label =  ('Dark Silver')},
			{ index = 20, label =  ('Magnesite')},
			{ index = 22, label =  ('Nickel')},
			{ index = 23, label =  ('Zinc')},
			{ index = 24, label =  ('Dolomite')},
			{ index = 25, label =  ('Blue Silver')},
			{ index = 26, label =  ('Titanium')},
			{ index = 66, label =  ('Steel Blue')},
			{ index = 93, label =  ('Champagne')},
			{ index = 144, label =  ('Grayhunter')},
			{ index = 156, label =  ('Grey')},
			{ index = 27, label =  ('Red')},
			{ index = 28, label =  ('Torino Red')},
			{ index = 29, label =  ('Poppy')},
			{ index = 30, label =  ('Copper Red')},
			{ index = 31, label =  ('Cardinal Red')},
			{ index = 32, label =  ('Brick Red ')},
			{ index = 33, label =  ('Garnet Red')},
			{ index = 34, label =  ('Cabernet Red')},
			{ index = 35, label =  ('Candy Red')},
			{ index = 39, label =  ('Matte Red')},
			{ index = 40, label =  ('Dark Red')},
			{ index = 43, label =  ('Red Pulp')},
			{ index = 44, label =  ('Brilliant Red')},
			{ index = 46, label =  ('Pale Red')},
			{ index = 143, label =  ('Wine Red')},
			{ index = 150, label =  ('Volcano')},
			{ index = 135, label =  ('Electric Pink')},
			{ index = 136, label =  ('Salmon')},
			{ index = 137, label =  ('Sugar Plum')},
			{ index = 54, label =  ('Topaz')},
			{ index = 60, label =  ('Light Blue')},
			{ index = 61, label =  ('Galaxy Blue')},
			{ index = 62, label =  ('Dark Blue')},
			{ index = 63, label =  ('Azure')},
			{ index = 64, label =  ('Navy Blue')},
			{ index = 65, label =  ('Lapis')},
			{ index = 67, label =  ('Blue Diamond')},
			{ index = 68, label =  ('Surfer')},
			{ index = 69, label =  ('Pastel Blue')},
			{ index = 70, label =  ('Celeste Blue')},
			{ index = 73, label =  ('Rally Blue')},
			{ index = 74, label =  ('Paradise Blue')},
			{ index = 75, label =  ('Blue Night')},
			{ index = 77, label =  ('Cyan Blue')},
			{ index = 78, label =  ('Cobalt')},
			{ index = 79, label =  ('Electric Blue')},
			{ index = 80, label =  ('Horizon Blue')},
			{ index = 82, label =  ('Metallic Blue')},
			{ index = 83, label =  ('Aquamarine')},
			{ index = 84, label =  ('Blue Agathe')},
			{ index = 85, label =  ('Zirconium')},
			{ index = 86, label =  ('Spinel')},
			{ index = 87, label =  ('Tourmaline')},
			{ index = 127, label =  ('Paradise')},
			{ index = 140, label =  ('Bubble Gum')},
			{ index = 141, label =  ('Midnight Blue')},
			{ index = 146, label =  ('Forbidden Blue')},
			{ index = 157, label =  ('Glacier Blue')},
			{ index = 42,  label =  ('Yellow')},
			{ index = 88,  label =  ('Wheat')},
			{ index = 89,  label =  ('Race Yellow')},
			{ index = 91,  label =  ('Pale Yellow')},
			{ index = 126, label =  ('Light Yellow')},
			{ index = 49,  label =  ('Metallic Dark Green')},
			{ index = 50,  label =  ('Rally Green')},
			{ index = 51,  label =  ('Pine Green')},
			{ index = 52,  label =  ('Olive Green')},
			{ index = 53,  label =  ('Light Green')},
			{ index = 55,  label =  ('Lime Green')},
			{ index = 56,  label =  ('Forest Green')},
			{ index = 57,  label =  ('Lawn Green')},
			{ index = 58,  label =  ('Imperial Green')},
			{ index = 59,  label =  ('Green Bottle')},
			{ index = 92,  label =  ('Citrus Green')},
			{ index = 125, label =  ('Green Anis')},
			{ index = 128, label =  ('Khaki')},
			{ index = 133, label =  ('Army Green')},
			{ index = 151, label =  ('Dark Green')},
			{ index = 152, label =  ('Hunter Green')},
			{ index = 155, label =  ('Matte Foilage Green')},
			{ index = 36,  label =  ('Tangerine')},
			{ index = 38,  label =  ('Orange')},
			{ index = 41,  label =  ('Matte Orange')},
			{ index = 123, label =  ('Light Orange')},
			{ index = 124, label =  ('Peach')},
			{ index = 130, label =  ('Pumpkin')},
			{ index = 138, label =  ('Orange Lambo')},
			{ index = 45,  label =  ('Copper')},
			{ index = 47,  label =  ('Light Brown')},
			{ index = 48,  label =  ('Dark Brown')},
			{ index = 90,  label =  ('Bronze')},
			{ index = 94,  label =  ('Brown Metallic')},
			{ index = 95,  label =  ('Expresso')},
			{ index = 96,  label =  ('Chocolate')},
			{ index = 97,  label =  ('Terra Cotta')},
			{ index = 98,  label =  ('Marble')},
			{ index = 99,  label =  ('Sand')},
			{ index = 100, label =  ('Sepia')},
			{ index = 101, label =  ('Bison')},
			{ index = 102, label =  ('Palm')},
			{ index = 103, label =  ('Caramel')},
			{ index = 104, label =  ('Rust')},
			{ index = 105, label =  ('Chestnut')},
			{ index = 108, label =  ('Brown')},
			{ index = 109, label =  ('Hazelnut')},
			{ index = 110, label =  ('Shell')},
			{ index = 114, label =  ('Mahogany')},
			{ index = 115, label =  ('Cauldron')},
			{ index = 116, label =  ('Blonde')},
			{ index = 129, label =  ('Gravel')},
			{ index = 153, label =  ('Dark Earth')},
			{ index = 154, label =  ('Desert')},
			{ index = 71,  label =  ('Indigo')},
			{ index = 72,  label =  ('Deep Purple')},
			{ index = 76,  label =  ('Dark Violet')},
			{ index = 81,  label =  ('Amethyst')},
			{ index = 142, label =  ('Mystical Violet')},
			{ index = 145, label =  ('Purple Metallic')},
			{ index = 148, label =  ('Matte Violet')},
			{ index = 149, label =  ('Matte Deep Purple')},
			{ index = 117, label =  ('Brushed Chrome')},
			{ index = 118, label =  ('Black Chrome')},
			{ index = 119, label =  ('Brushed Aluminum')},
			{ index = 120, label =  ('Chrome')},
			{ index = 37,  label =  ('Gold')},
			{ index = 158, label =  ('Pure Gold')},
			{ index = 159, label =  ('Brushed Gold')},
			{ index = 160, label =  ('Light Gold')}
    }
    for i=1,#colors,1 do
        if colors[i].index == colorID then
            return colors[i].label
        end
    end
end