Citizen.CreateThread(function()
	local blip = AddBlipForCoord(982.40, -103.50, 74.85)
	    SetBlipSprite (blip, 494)
		SetBlipDisplay(blip, 4)
		SetBlipScale  (blip, 1.0)
		SetBlipColour (blip, 60)
		SetBlipAsShortRange(blip, true)
		BeginTextCommandSetBlipName("STRING")
		AddTextComponentString("Sinners MC")
		EndTextCommandSetBlipName(blip)
end)